// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.badges",
  "name": "Badges for Mattermost",
  "description": "This plugin add badges support to Mattermost.",
  "homepage_url": "https://github.com/larkox/mattermost-plugin-badges",
  "support_url": "https://github.com/larkox/mattermost-plugin-badges/issues",
  "release_notes_url": "https://github.com/larkox/mattermost-plugin-badges/releases/tag/v0.2.1",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "0.2.1",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "BadgesAdmin",
        "display_name": "Badges admin:",
        "type": "text",
        "help_text": "This user will be considered as an admin for the badges plugin. They can create types, and modify and grant any badge.",
        "placeholder": "",
        "default": null,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	manifest = &model.Manifest{}
	if err := json.Unmarshal([]byte(manifestStr), manifest); err != nil {
		panic("failed to unmarshal manifest: " + err.Error())
	}
}
